version: '3.5'

services:
  db_cinema:
    container_name: db_cinema
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:15rc2-alpine
